# Test Case 1: checking if BaseGeometry can be instantiated and also checking if we can make an object of it
>>> Base_geometry = __import__('7-base_geometry').BaseGeometry
>>> bg = Base_geometry()
>>> type(bg) is Base_geometry
True

# Test Case 2: checking if area method raises an exception with the area() is not implemented massege
>>> bg.area()
Traceback (most recent call last):
...
Exception: area() is not implemented

# Test Case 3: checking if integer_validator method raises a TypeError with the message <name> must be an integer, when value is not integer
>>> bg.integer_validator('Hello', 'Hi')
Traceback (most recent call last):
...
TypeError: Hello must be an integer

# Test Case 4: checking if integer_validator method raises a valueError with the message <name> must be greater than 0
>>> bg.integer_validator('Hi', -1)
Traceback (most recent call last):
...
ValueError: Hi must be greater than 0

# Test Case 5: checking if it does't rise any exception if no less than 0 or non-integer value is passed as arg
>>> bg.integer_validator('Hello', 6)

# Test Case 6: checking if it raises a TypeError wehen no arguments are not passed
>>> bg.integer_validator()
Traceback (most recent call last):
...
TypeError: integer_validator() missing 2 required positional arguments: 'name' and 'value'

# Test Case 7: checking if it raises a ValueError when 0 passes as a value of value parameter
>>> bg.integer_validator('Hi', 0)
Traceback (most recent call last):
...
ValueError: Hi must be greater than 0

# Test Case 8: checking the method raises a TypeError when a Tuple, list, bool, None are passed as value of value parameter
>>> bg.integer_validator('Hello', (4,))
Traceback (most recent call last):
...
TypeError: Hello must be an integer
>>> bg.integer_validator("Hello", [2])
Traceback (most recent call last):
...
TypeError: Hello must be an integer
>>> bg.integer_validator('Hello', True)
Traceback (most recent call last):
...
TypeError: Hello must be an integer
>>> bg.integer_validator("Hello", None)
Traceback (most recent call last):
...
TypeError: Hello must be an integer
>>> bg.integer_validator("Hello", {2, 3})
Traceback (most recent call last):
...
TypeError: Hello must be an integer
